plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: "auto-web*"
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
hostnames:
  - tag:Name

